destination: docs

collections:
  blogs:
    output: true

title: "ZhongUncle's Blog"
# description: 

url: "https://zhonguncle.github.io"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

social:
  name: ZhongUncle
  links:
    - https://blog.csdn.net/qq_33919450
    - https://github.com/zhonguncle